version: 2
updates:
  - package-ecosystem: maven
    directory: "/sso-jwt-resource"
    schedule:
      interval: daily
      time: '21:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10

  - package-ecosystem: maven
    directory: "/sso-jwt"
    schedule:
      interval: daily
      time: '21:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
